### ISSUE TITLE
more than 1 pod => infinite loop and never deploy

### ISSUE THREAD

**Issue by flbla** [bohlenc/k8s-pod-mutator-webhook#5]
Hi @bohlenc 

if I deploy more than one pod, it goes in too infinite loop 
eg, I have those 2 deployments :
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
```

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment2
  labels:
    app: nginx2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
      - name: nginx2
        image: nginx:alpine
        ports:
        - containerPort: 80
```

with this path configuration :

```
webhook:
  patch: |
    spec:
      initContainers:
      - name: ca
        image: alpine
        command: ["sh", "-c", "cp -r /etc/ssl/certs /volume"]
        volumeMounts:
        - mountPath: /volume
          name: cacerts
      containers:
      - name: "*"
        volumeMounts:
        - mountPath: /etc/ssl
          name: cacerts
      volumes:
      - name: cacerts
        emptyDir: {}
```

I also tried with a named container instead of "*", same issue
